user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar_size: 80
  thumb_size: 50
  per_page: 10
category:
  name:
    max_length: 255
comment:
  content:
    max_length: 500
comic:
  name:
    max_length: 100
  author:
    max_length: 100
  description:
    max_length: 2000
  thumb_size: 10
  thumb:
    width: 720
    height: 960
chapter:
  name:
    max_length: 50
